import { Trash } from "lucide-react";
import Head from "next/head";
import Link from "next/link";
import CreateProject from "~/components/shared/dialogs/create-project";
import { Button } from "~/components/ui/button";

import { api } from "~/utils/api";

export default function Home() {
  // const createProject = api.project.create.useMutation();

  const { data, isLoading, isRefetching } = api.project.getLatest.useQuery();

  if (isLoading || isRefetching) return <div>Loading...</div>;
  // console.log({ project: project.data });
  if (data)
    return (
      <>
        <Head>
          <title>Project Management App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" flex min-h-screen flex-col gap-4 p-4">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-semibold">Your Projects</h1>
            <CreateProject />{" "}
          </div>
          <div className="grid grid-cols-2 gap-4">
            {Array.isArray(data) &&
              data.length > 0 &&
              data.map((item) => {
                return (
                  <div
                    key={item.id}
                    className="col-span-1 flex items-center justify-between rounded-md border p-2 hover:bg-gray-300"
                  >
                    <Link href={`/${item.id}`} className="hover:text-blue-600">
                      {item.name}
                    </Link>
                    <Button variant={"outline"} size={"icon"}>
                      <Trash />
                    </Button>
                  </div>
                );
              })}
          </div>
        </main>
      </>
    );
}
