import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";

import { api } from "~/utils/api";

export default function Home() {
  const createProject = api.project.create.useMutation();
  const handleClick = () => {
    const name = "Third project";
    createProject.mutate({ name });
  };
  const project = api.project.getLatest.useQuery();
  console.log({ project: project.data });
  if (project)
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" flex min-h-screen flex-col items-center justify-center ">
          <Button variant={"outline"} onClick={() => handleClick()}>
            Create Project
          </Button>
          {Array.isArray(project.data) &&
            project.data.map((item) => {
              return (
                <div key={item.id}>
                  <Link href={`/${item.id}`}>{item.name}</Link>
                </div>
              );
            })}

          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <div className="flex flex-col items-center gap-2">
              <AuthShowcase />
            </div>
          </div>
        </main>
      </>
    );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
